swagger: '2.0'
info:
  version:
  title:
  license:
    name:
paths:
  /api/api/user/user/info:
    get:
      summary: 用户信息
      tags:
        - 用户
      operationId: userInfo
      parameters:
        - name: token
          in: query
          description: token
          type: string
          required: true
      responses:
        200:
          description: |
            username：用户名
            email：email
            created_at：注册时间
            updated_at：最后修改时间
            status：状态 1：正常 -2：删除 -1：禁用 2：未激活(待验证)

            ```json
            {
              "code":18000,
              "msg":"",
              "data":{
                "username":"soliang",
                "email":"297210725@qq.com",
                "status":1,
                "created_at":"2019-06-22 14:12:22",
                "updated_at":"2019-06-22 14:12:22"
              }
            }
            ```
