swagger: "2.0"
info:
  description: "Sheet Api 接口文档 [`api`](/api/documentation). "
  version: "1.0.0"
  title: "Sheet Api"
  #  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "soliang@dingtalk.com"
  #    name: "soliang"
  #    url: "test"
  license:
    name: "admin 接口文档地址"
    url: "/admin/documentation"
#basePath: "/"
tags:
  - name: "用户注册登录"
    description: "用户注册登录相关接口"
    externalDocs:
      description: ""
      url: ""
  - name: "用户"
    description: "用户相关接口"
paths:

